### ISSUE TITLE
Cache-Control: should we set max-age=0?

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/nocache#6]
Reading the [RFC for Cache-Control](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.3) makes me think we should set `max-age=0` in the directive. Is this correct?

**Comment by analog-nico** [comment]
`Cache-Control: no-cache no-store` already ensures that HTTP/1.1 clients don't cache the resource. Since HTTP/1.1 clients understand both parameters `max-age=0` is not necessary IMO. At least I didn't find any sentences in the spec that either recommend its use or say anything against it. So even adding it wouldn't hurt. However, I found in section [14.21 Expires](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.21): `HTTP/1.1 clients and caches MUST treat other invalid date formats [as the value of the Expires header], especially including the value "0", as in the past (i.e., "already expired").` This means that already sending `Expires: 0` is sufficient and sending `max-age=0` is really not needed anymore.

Since I don't know all the clients out in the wild maybe there are some wrongly implemented ones that would benefit from `max-age=0`. But then again there might be some wrongly implemented clients which missed this sentence in section 14.9.3.: `The max-age directive on a response implies that the response is cacheable (i.e., "public") unless some other, more restrictive cache directive is also present.` Altogether I would personally not include `max-age=0` to keep the headers DRY.

**Comment by EvanHahn** [comment]
Good call. Closing.

Thanks for all your help!

**Comment by analog-nico** [comment]
Of course. Investing time into the helmet libraries is always worth it!
